# Generated by Django 5.1.7 on 2025-03-13 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_model_data_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='model_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.model_data'),
        ),
    ]
