# Generated by Django 5.1.7 on 2025-03-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_material_model_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='custom_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
