# Generated by Django 5.1.7 on 2025-03-14 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_customer_custom_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={},
        ),
        migrations.AlterModelOptions(
            name='menuaccess',
            options={},
        ),
        migrations.RemoveField(
            model_name='menu',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='description',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='menu_icon_path',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='order',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='url',
        ),
        migrations.RemoveField(
            model_name='menuaccess',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='menuaccess',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='menuaccess',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='menuaccess',
            name='permission_id',
        ),
        migrations.RemoveField(
            model_name='menuaccess',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='menuaccess',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuaccess',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuaccess',
            name='can_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuaccess',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='level',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
