# Generated by Django 5.1.7 on 2025-03-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_auth', '0008_remove_menuaccess_can_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
