# Generated by Django 5.1.7 on 2025-03-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_auth', '0009_branch_permissions_alter_branch_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='permissions',
        ),
        migrations.AddField(
            model_name='userrole',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.permission'),
        ),
    ]
