# Generated by Django 5.1.7 on 2025-03-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0011_materialdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_sleeve',
            field=models.CharField(blank=True, choices=[('full', 'Full Sleeve'), ('sleeveless', 'Sleeveless'), ('half', 'Half Sleeve')], max_length=20, null=True),
        ),
    ]
