# Generated by Django 5.1.7 on 2025-03-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0012_alter_item_is_sleeve'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
