# Generated by Django 5.1.7 on 2025-03-18 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0013_customer_business_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.materialdata'),
        ),
    ]
