# Generated by Django 5.1.7 on 2025-03-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0014_alter_item_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
