# Generated by Django 5.1.7 on 2025-04-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0021_alter_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
