# Generated by Django 5.1.7 on 2025-04-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0022_alter_item_item_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_sleeve',
            field=models.CharField(blank=True, choices=[('full', 'Full Sleeve'), ('sleeveless', 'Sleeveless'), ('half', 'Half Sleeve'), ('design', 'Design'), ('plain', 'Plain'), ('dtf', 'DTF'), ('embroidery', 'Embroidery')], max_length=20, null=True),
        ),
    ]
