# Generated by Django 5.1.7 on 2025-04-10 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0023_alter_item_is_sleeve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='branch',
        ),
        migrations.AlterField(
            model_name='item',
            name='is_sleeve',
            field=models.CharField(blank=True, choices=[('full', 'Full Sleeve'), ('sleeveless', 'Sleeveless'), ('half', 'Half Sleeve')], max_length=20, null=True),
        )
    ]
