# Generated by Django 5.1.7 on 2025-04-10 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0025_alter_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_branch', to='user_auth.branch'),
        ),
        migrations.AddField(
            model_name='printtype',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.model_data'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_sleeve',
            field=models.CharField(blank=True, choices=[('full', 'Full Sleeve'), ('sleeveless', 'Sleeveless'), ('half', 'Half Sleeve'), ('design', 'Design'), ('plain', 'Plain'), ('dtf', 'DTF'), ('embroidery', 'Embroidery')], max_length=20, null=True),
        )
    ]
