# Generated by Django 5.1.7 on 2025-04-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0027_remove_unique_from_itemcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_sleeve',
            field=models.CharField(blank=True, choices=[('FULL SLEEVE', 'FULL SLEEVE'), ('SLEEVELESS', 'SLEEVELESS'), ('HALF SLEEVE', 'HALF SLEEVE')], max_length=20, null=True),
        ),
    ]
