# Generated by Django 5.1.7 on 2025-04-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0028_alter_item_is_sleeve'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='GSTN',
            field=models.CharField(default='GST01020', max_length=100),
        ),
        migrations.AddField(
            model_name='branch',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='phn_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='pincode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='state',
            field=models.CharField(default='KERALA', max_length=100),
        ),
    ]
