# Generated by Django 5.1.7 on 2025-04-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0029_branch_gstn_branch_email_branch_phn_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='account_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
