# Generated by Django 5.1.7 on 2025-04-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0030_branch_account_details_branch_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='qr_code',
            field=models.FileField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
