# Generated by Django 5.1.7 on 2025-05-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0032_state_shippingcustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
