# Generated by Django 5.1.7 on 2025-05-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0033_branch_upi_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingcustomer',
            name='mobile_number1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
