# Generated by Django 5.1.7 on 2025-05-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0034_alter_shippingcustomer_mobile_number1'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='logos'),
        ),
    ]
