# Generated by Django 5.1.7 on 2025-05-07 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0035_branch_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.state'),
        ),
    ]
