# Generated by Django 5.1.7 on 2025-05-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0036_customer_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pincode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
