# Generated by Django 5.1.7 on 2025-06-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0037_customer_address3_customer_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='HSN',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
