# Generated by Django 5.1.7 on 2025-06-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0038_item_hsn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='HSN',
            field=models.CharField(blank=True, default='610990', max_length=20, null=True),
        ),
    ]
