# Generated by Django 5.1.7 on 2026-02-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0039_alter_item_hsn'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='branch',
            field=models.ManyToManyField(blank=True, related_name='customers', to='user_auth.branch'),
        ),
    ]
