# Generated by Django 5.1.7 on 2025-03-19 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0015_alter_item_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=100, unique=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('gst', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('net_cost', models.CharField(blank=True, max_length=30, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='logos/')),
                ('front_matter', models.CharField(blank=True, max_length=255, null=True)),
                ('front_img', models.FileField(blank=True, null=True, upload_to='front_images/')),
                ('back_matter', models.CharField(blank=True, max_length=255, null=True)),
                ('back_img', models.FileField(blank=True, null=True, upload_to='back_images/')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.customer')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('qty', models.PositiveIntegerField(blank=True, null=True)),
                ('sleeve_case', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Order.invoice')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.item')),
            ],
        ),
        migrations.CreateModel(
            name='Orderdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderID', models.CharField(max_length=100, unique=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('net_cost', models.CharField(blank=True, max_length=30, null=True)),
                ('gst', models.CharField(blank=True, max_length=30, null=True)),
                ('total_cost', models.CharField(blank=True, max_length=30, null=True)),
                ('delivery_date', models.DateField()),
                ('logo', models.FileField(blank=True, null=True, upload_to='logos/')),
                ('front_matter', models.CharField(blank=True, max_length=255, null=True)),
                ('front_img', models.FileField(blank=True, null=True, upload_to='front_images/')),
                ('back_matter', models.CharField(blank=True, max_length=255, null=True)),
                ('back_img', models.FileField(blank=True, null=True, upload_to='back_images/')),
                ('Completed_payment', models.BooleanField(default=False)),
                ('invoice_flag', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.customer')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Order.orderdata'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('qty', models.PositiveIntegerField(blank=True, null=True)),
                ('discount', models.CharField(blank=True, max_length=50, null=True)),
                ('total_item_cost', models.CharField(blank=True, max_length=50, null=True)),
                ('sleeve_case', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.item')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='Order.orderdata')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='order_item_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Order.orderitem'),
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('balance_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_created_by', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.customer')),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Order.orderdata')),
            ],
        ),
    ]
