# Generated by Django 5.1.7 on 2025-03-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_invoice_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Inprogress', 'Inprogress'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Pending', max_length=100, null=True),
        ),
    ]
