# Generated by Django 5.1.7 on 2025-03-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='total_cost',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
