# Generated by Django 5.1.7 on 2025-03-13 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_orderdata_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdata',
            name='item',
        ),
    ]
