# Generated by Django 5.1.7 on 2025-04-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_invoiceitem_discount_invoiceitem_total_item_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
