# Generated by Django 5.1.7 on 2025-04-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_orderdata_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='discount',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
