# Generated by Django 5.1.7 on 2025-03-17 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_orderdata_gst_orderdata_net_cost_orderitem_discount_and_more'),
        ('user_auth', '0013_customer_business_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdata',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.customer'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_auth.item'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='Order.orderdata'),
        ),
    ]
