# Generated by Django 5.1.7 on 2025-05-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_orderdata_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='qr_code',
            field=models.FileField(blank=True, null=True, upload_to='invoice_qr/'),
        ),
    ]
