# Generated by Django 5.1.7 on 2025-03-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0007_alter_orderdata_customer_alter_orderitem_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='Completed_payment',
            field=models.BooleanField(default=False),
        ),
    ]
