# Generated by Django 5.1.7 on 2025-05-06 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0007_orderdata_qr_code'),
        ('user_auth', '0034_alter_shippingcustomer_mobile_number1'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='parcel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderdata',
            name='shipped_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipped_orders', to='user_auth.shippingcustomer'),
        ),
    ]
