# Generated by Django 5.1.7 on 2025-05-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0008_orderdata_parcel_orderdata_shipped_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='refund_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
