# Generated by Django 5.1.7 on 2025-03-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0008_orderdata_completed_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='invoice_flag',
            field=models.BooleanField(default=False),
        ),
    ]
