# Generated by Django 5.1.7 on 2025-05-31 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0009_orderpayment_refund_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='gst',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='balance_amount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='paid_amount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='total_amount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
