# Generated by Django 5.1.7 on 2025-07-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0011_alter_invoiceitem_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='order_invoice',
            field=models.BooleanField(default=False),
        ),
    ]
