# Generated by Django 5.1.7 on 2025-07-14 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0013_alter_invoice_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Order.orderitem'),
        ),
        migrations.AddField(
            model_name='orderdata',
            name='order_invoice_sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderdata',
            name='order_invoice',
            field=models.CharField(blank=True, default='PENDING', max_length=100, null=True),
        ),
    ]
