# Generated by Django 5.1.7 on 2025-07-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0015_alter_orderdata_discount_alter_orderdata_gst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdata',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
