# Generated by Django 5.1.7 on 2025-07-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0016_alter_orderdata_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='net_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
