# Generated by Django 5.1.7 on 2025-08-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0018_alter_invoice_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdata',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
